# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d2f5c5bcb1e00608bce495fe6f3c9decc9cac25080bb580bf4efa90b05dcdab639ae89cf311620f8d3e0b51932794fe7440b05f5f6c350bbbb479f7423d93729

test:
  secret_key_base: 4e11809cb60cfbcf56ce166e4d6e338754af3b7e85c28ba4e255b9e74b05bead3b1abaad93dacef903ccf875c15f46e434b866308d7a0592f0e27aaffcb3ac3c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
